"""Testing lab & evaluation routes."""

from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.deps import get_optional_current_user
from app.db.session import get_db
from app.models.persona import Memory, PersonaCore, WritingSample
from app.models.policy import PolicyRule
from app.models.testing import Evaluation, TestResult, TestScenario
from app.models.user import User
from app.schemas.core import (
    CloneRequest,
    CloneResponse,
    EvaluationCreate,
    EvaluationRead,
    ImprovementSuggestion,
    TestScenarioCreate,
    TestScenarioRead,
)

router = APIRouter(prefix="/testing", tags=["Testing Lab"])

SCENARIO_LOAD = selectinload(TestScenario.results).selectinload(TestResult.evaluations)


# ── Scenarios ────────────────────────────────────────────


@router.post("/scenarios", response_model=TestScenarioRead, status_code=201)
async def create_scenario(data: TestScenarioCreate, db: AsyncSession = Depends(get_db)):
    scenario = TestScenario(**data.model_dump(exclude_none=True))
    db.add(scenario)
    await db.flush()
    await db.refresh(scenario)
    return scenario


@router.get("/scenarios", response_model=list[TestScenarioRead])
async def list_scenarios(
    persona_id: UUID = Query(...),
    context_type: str | None = None,
    db: AsyncSession = Depends(get_db),
):
    stmt = (
        select(TestScenario)
        .options(SCENARIO_LOAD)
        .where(TestScenario.persona_id == persona_id)
        .order_by(TestScenario.created_at.desc())
    )
    if context_type:
        stmt = stmt.where(TestScenario.context_type == context_type)
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.get("/scenarios/{scenario_id}", response_model=TestScenarioRead)
async def get_scenario(scenario_id: UUID, db: AsyncSession = Depends(get_db)):
    stmt = (
        select(TestScenario)
        .options(SCENARIO_LOAD)
        .where(TestScenario.id == scenario_id)
    )
    result = await db.execute(stmt)
    scenario = result.scalar_one_or_none()
    if not scenario:
        raise HTTPException(status_code=404, detail="Scenario not found")
    return scenario


# ── Run clone ────────────────────────────────────────────


@router.post("/run", response_model=CloneResponse)
async def run_clone(
    req: CloneRequest,
    db: AsyncSession = Depends(get_db),
    user: User | None = Depends(get_optional_current_user),
):
    """Execute the clone pipeline for a single message.

    This route orchestrates the full clone generation flow:
    classify → retrieve → generate → critique → respond.
    """
    # Import here to avoid circular imports during startup
    from app.services.clone_engine import CloneEngine

    engine = CloneEngine(db)
    return await engine.generate(req, user=user)


# ── Evaluations ──────────────────────────────────────────


@router.post("/evaluations", response_model=EvaluationRead, status_code=201)
async def create_evaluation(data: EvaluationCreate, db: AsyncSession = Depends(get_db)):
    evaluation = Evaluation(**data.model_dump(exclude_none=True))
    db.add(evaluation)
    await db.flush()
    await db.refresh(evaluation)
    return evaluation


@router.get("/evaluations", response_model=list[EvaluationRead])
async def list_evaluations(
    test_result_id: UUID = Query(...), db: AsyncSession = Depends(get_db)
):
    stmt = (
        select(Evaluation)
        .where(Evaluation.test_result_id == test_result_id)
        .order_by(Evaluation.created_at.desc())
    )
    result = await db.execute(stmt)
    return list(result.scalars().all())


# ── Apply improvement suggestion ─────────────────────────


class ApplyFixRequest(BaseModel):
    persona_id: UUID
    suggestion: ImprovementSuggestion


class ApplyFixResponse(BaseModel):
    applied: bool
    detail: str
    created_id: str | None = None


@router.post("/apply-fix", response_model=ApplyFixResponse)
async def apply_fix(data: ApplyFixRequest, db: AsyncSession = Depends(get_db)):
    """Apply a single improvement suggestion generated by the auto-evaluator.

    Supports creating memories, writing samples, policies, and updating
    the persona's never_say list.
    """
    suggestion = data.suggestion
    persona = await db.get(PersonaCore, data.persona_id)
    if not persona:
        raise HTTPException(status_code=404, detail="Persona not found")

    if suggestion.type == "memory":
        memory = Memory(
            persona_id=data.persona_id,
            memory_type=suggestion.payload.get("memory_type", "fact"),
            title=suggestion.payload.get("title", suggestion.title),
            content=suggestion.payload.get("content", ""),
            source=suggestion.payload.get("source", "testing_lab_auto"),
            confidence=suggestion.payload.get("confidence", 0.85),
            tags=suggestion.payload.get("tags"),
            linked_entities=suggestion.payload.get("linked_entities"),
            approval_status="approved",
        )
        db.add(memory)
        await db.flush()
        await db.refresh(memory)
        return ApplyFixResponse(
            applied=True,
            detail=f"Memory '{memory.title}' created.",
            created_id=str(memory.id),
        )

    elif suggestion.type == "writing_sample":
        sample = WritingSample(
            persona_id=data.persona_id,
            content=suggestion.payload.get("content", ""),
            context_type=suggestion.payload.get("context_type", "general"),
            is_representative=suggestion.payload.get("is_representative", True),
            notes=suggestion.payload.get("notes"),
        )
        db.add(sample)
        await db.flush()
        await db.refresh(sample)
        return ApplyFixResponse(
            applied=True,
            detail=f"Writing sample added ({suggestion.payload.get('context_type', 'general')} context).",
            created_id=str(sample.id),
        )

    elif suggestion.type == "policy":
        rule = PolicyRule(
            persona_id=data.persona_id,
            policy_type=suggestion.payload.get("policy_type", "guardrail"),
            name=suggestion.payload.get("name", suggestion.title),
            description=suggestion.payload.get("description", ""),
            priority=suggestion.payload.get("priority", 5),
        )
        db.add(rule)
        await db.flush()
        await db.refresh(rule)
        return ApplyFixResponse(
            applied=True,
            detail=f"Policy rule '{rule.name}' created.",
            created_id=str(rule.id),
        )

    elif suggestion.type == "never_say":
        phrases = suggestion.payload.get("phrases", [])
        current = list(persona.never_say or [])
        added = [p for p in phrases if p not in current]
        if added:
            persona.never_say = current + added
            await db.flush()
            await db.refresh(persona)
        return ApplyFixResponse(
            applied=True,
            detail=f"Added {len(added)} phrase(s) to never_say: {', '.join(repr(p) for p in added)}.",
        )

    else:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown suggestion type: {suggestion.type}",
        )
